---
title: "Demand Paper"
author: "Matthew Aaron Looney"
date: "08/22/2017"
output:
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 4
  html_document:
    toc: yes
    toc_depth: '4'
header-includes:
- \usepackage{graphicx}
- \usepackage{rotating}
- \usepackage{longtable}
- \usepackage{amssymb,amsmath}
- \usepackage{dcolumn}
---

```{r House Keeping, echo=FALSE, message=FALSE}

rm(list=ls())

# randNum <- round(runif(1, 1, 1e8)) # !!! RUN ONLY ONCE TO GENERATE RN for seed !!!
# randNum
set.seed(38532842) # all sequential simulations will start from this seed

library(readxl)
library(stargazer)
library(systemfit)
library(np)
library(micEconAids)

options(np.messages=FALSE) 
#options(digits=5)

setwd("~/Google Drive/digitalLibrary/*AAEC 6310 Demand and Price Analysis/DLDemand_nonparametric")

source("~/Google Drive/digitalLibrary/*AAEC 6310 Demand and Price Analysis/demandLab1/calculate_pValue.R")
source("~/Google Drive/digitalLibrary/*AAEC 6310 Demand and Price Analysis/demandLab1/calculate_tValues.R")

```

```{r Import & data manip, echo=FALSE, message=FALSE}

Dta <- read.csv("/Users/malooney/Google Drive/digitalLibrary/*Econometrics2/Lab3/protein.csv")
Dta_sub <- data.frame(obs=1:nrow(Dta))

Dta_sub$p1 <- Dta$pmeats1
Dta_sub$p2 <- Dta$pdairy1
Dta_sub$p3 <- Dta$ppulses1

Dta_sub$q1 <- Dta$qmeats
Dta_sub$q2 <- Dta$qdairy
Dta_sub$q3 <- Dta$qpulses

Dta_sub$p1q1 <- Dta$qmeats*Dta$pmeats1
Dta_sub$p2q2 <- Dta$qdairy*Dta$pdairy1
Dta_sub$p3q3 <- Dta$ppulses1*Dta$qpulses

Dta_sub$X <- Dta_sub$p1q1 + Dta_sub$p2q2 + Dta_sub$p3q3

Dta_sub$w1 <- Dta_sub$p1q1 / Dta_sub$X
Dta_sub$w2 <- Dta_sub$p2q2 / Dta_sub$X
Dta_sub$w3 <- Dta_sub$p3q3 / Dta_sub$X

Dta_sub_log <- Dta_sub
Dta_sub_log <- log(Dta_sub[,c(2:7,11)])

```

```{r Single Equation Model Estimation using Log-Log Functional Form, echo=FALSE, message=FALSE}

# Single Equation Model Estimation using Log-Log Functional Form
# Estimate Marshallian elasticities - unrestricted

dld_marshallian_1.lm <- lm(q1 ~ p1+ p2+ p3+ X, data=Dta_sub_log)
dld_marshallian_2.lm <- lm(q2 ~ p1+ p2+ p3+ X, data=Dta_sub_log)
dld_marshallian_3.lm <- lm(q3 ~ p1+ p2+ p3+ X, data=Dta_sub_log)

# summary(dld_marshallian_1.lm)
# summary(dld_marshallian_2.lm)
# summary(dld_marshallian_3.lm)

exx_par <- matrix(unlist(c(coef(dld_marshallian_1.lm)[2:5], coef(dld_marshallian_2.lm)[2:5], coef(dld_marshallian_3.lm)[2:5])), nrow = 3, byrow = TRUE)

```
  
```{r, echo=FALSE, message=FALSE, fig.height=3}

dld_1_formula <- formula(q1 ~ p1+ p2+ p3+ X)
dld_2_formula <- formula(q2 ~ p1+ p2+ p3+ X)
dld_3_formula <- formula(q3 ~ p1+ p2+ p3+ X)

xdat <- Dta_sub_log[,c(1:3, 7)]
ydat_1 <- Dta_sub_log$q1
ydat_2 <- Dta_sub_log$q2
ydat_3 <- Dta_sub_log$q3

dld_1 <- lm(q1 ~ p1+ p2+ p3+ X, data=Dta_sub_log, x=TRUE, y=TRUE)
dld_2 <- lm(q2 ~ p1+ p2+ p3+ X, data=Dta_sub_log, x=TRUE, y=TRUE)
dld_3 <- lm(q3 ~ p1+ p2+ p3+ X, data=Dta_sub_log, x=TRUE, y=TRUE)

### !!! time consuming code - only run when chaging code !!! ###
### Consistent Model Specification Test
# cmsTest_1 <- npcmstest(model=dld_1, xdat=xdat, ydat = ydat_1)
# cmsTest_2 <- npcmstest(model=dld_2, xdat=xdat, ydat = ydat_2)
# cmsTest_3 <- npcmstest(model=dld_3, xdat=xdat, ydat = ydat_3)
# 
# saveRDS(cmsTest_1, file= "Equaddata/cmsTest_1.rds")
# saveRDS(cmsTest_2, file= "Equaddata/cmsTest_2.rds")
# saveRDS(cmsTest_3, file= "Equaddata/cmsTest_3.rds")

cmsTest_1 <- readRDS("Equaddata/cmsTest_1.rds")
cmsTest_2 <- readRDS("Equaddata/cmsTest_2.rds")
cmsTest_3 <- readRDS("Equaddata/cmsTest_3.rds")

### !!! time consuming code - only run when chaging code !!! ###
### bandwidth calculations ###
# bw.all_1 <- npregbw(formula = dld_1_formula, regtype = "ll", bwmethod = "cv.aic", bwtype="fixed", ckertype= "gaussian", data = Dta_sub_log)
# bw.all_2 <- npregbw(formula = dld_2_formula, regtype = "ll", bwmethod = "cv.aic", bwtype="fixed", ckertype= "gaussian", data = Dta_sub_log)
# bw.all_3 <- npregbw(formula = dld_3_formula, regtype = "ll", bwmethod = "cv.aic", bwtype="fixed", ckertype= "gaussian", data = Dta_sub_log)
# 
# saveRDS(bw.all_1, file= "Equaddata/bw.all_1.rds")
# saveRDS(bw.all_2, file= "Equaddata/bw.all_2.rds")
# saveRDS(bw.all_3, file= "Equaddata/bw.all_3.rds")
# saveRDS(bw.all_1, file= "Equaddata/bw.all_1.1.rds")
# saveRDS(bw.all_2, file= "Equaddata/bw.all_2.1.rds")
# saveRDS(bw.all_3, file= "Equaddata/bw.all_3.1.rds")

# bw.all_1 <- readRDS("Equaddata/bw.all_1.rds")
# bw.all_2 <- readRDS("Equaddata/bw.all_2.rds")
# bw.all_3 <- readRDS("Equaddata/bw.all_3.rds")
bw.all_1 <- readRDS("Equaddata/bw.all_1.1.rds")
bw.all_2 <- readRDS("Equaddata/bw.all_2.1.rds")
bw.all_3 <- readRDS("Equaddata/bw.all_3.1.rds")

# summary(bw.all_1)
# summary(bw.all_2)
# summary(bw.all_3)

model_1.np <- npreg(bws = bw.all_1, gradients = TRUE, residuals = TRUE)
model_2.np <- npreg(bws = bw.all_2, gradients = TRUE, residuals = TRUE)
model_3.np <- npreg(bws = bw.all_3, gradients = TRUE, residuals = TRUE)

# summary(model_1.np)
# summary(model_2.np)
# summary(model_3.np)

### !!! time consuming code - only run when chaging code !!! ###
#Kernel Regression Significance Test
# KRS_test_1 <- npsigtest(model_1.np)
# KRS_test_2 <- npsigtest(model_2.np)
# KRS_test_3 <- npsigtest(model_3.np)
# 
# saveRDS(KRS_test_1, file= "Equaddata/KRS_test_1.rds")
# saveRDS(KRS_test_2, file= "Equaddata/KRS_test_2.rds")
# saveRDS(KRS_test_3, file= "Equaddata/KRS_test_3.rds")
# saveRDS(KRS_test_1, file= "Equaddata/KRS_test_1.1.rds")
# saveRDS(KRS_test_2, file= "Equaddata/KRS_test_2.1.rds")
# saveRDS(KRS_test_3, file= "Equaddata/KRS_test_3.1.rds")

# KRS_test_1 <- readRDS("Equaddata/KRS_test_1.rds")
# KRS_test_2 <- readRDS("Equaddata/KRS_test_2.rds")
# KRS_test_3 <- readRDS("Equaddata/KRS_test_3.rds")
KRS_test_1.1 <- readRDS("Equaddata/KRS_test_1.1.rds")
KRS_test_2.1 <- readRDS("Equaddata/KRS_test_2.1.rds")
KRS_test_3.1 <- readRDS("Equaddata/KRS_test_3.1.rds")

e1x_np <- list()
e1x_np$e11_np <- mean(model_1.np$grad[,1])
e1x_np$e12_np <- mean(model_1.np$grad[,2])
e1x_np$e13_np <- mean(model_1.np$grad[,3])
e1x_np$eta1_np <- mean(model_1.np$grad[,4])

e1x_np_t <- list()
e1x_np_t$e11_np_t <- mean(model_1.np$grad[,1])/mean(model_1.np$gerr[,1])
e1x_np_t$e12_np_t <- mean(model_1.np$grad[,2])/mean(model_1.np$gerr[,2])
e1x_np_t$e13_np_t <- mean(model_1.np$grad[,3])/mean(model_1.np$gerr[,3])
e1x_np_t$eta1_np_t <- mean(model_1.np$grad[,4])/mean(model_1.np$gerr[,4])

e2x_np <- list()
e2x_np$e21_np <- mean(model_2.np$grad[,1])
e2x_np$e22_np <- mean(model_2.np$grad[,2])
e2x_np$e23_np <- mean(model_2.np$grad[,3])
e2x_np$eta2_np <- mean(model_2.np$grad[,4])

e2x_np_t <- list()
e2x_np_t$e21_np_t <- mean(model_2.np$grad[,1])/mean(model_2.np$gerr[,1])
e2x_np_t$e22_np_t <- mean(model_2.np$grad[,2])/mean(model_2.np$gerr[,2])
e2x_np_t$e23_np_t <- mean(model_2.np$grad[,3])/mean(model_2.np$gerr[,3])
e2x_np_t$eta2_np_t <- mean(model_2.np$grad[,4])/mean(model_2.np$gerr[,4])

e3x_np <- list()
e3x_np$e31_np <- mean(model_3.np$grad[,1])
e3x_np$e32_np <- mean(model_3.np$grad[,2])
e3x_np$e33_np <- mean(model_3.np$grad[,3])
e3x_np$eta3_np <- mean(model_3.np$grad[,4])

par(mfrow=c(1,3))
plot(density(model_1.np$grad[,1]), sub = "Meats - own price elasticity", main= "", xlim=c(-5,5))
plot(density(model_2.np$grad[,2]), sub = "Dairy - own price elasticity", main= "",xlim=c(-5,5))
plot(density(model_3.np$grad[,3]), sub = "Pulses - own price elasticity", main= "", xlim=c(-5,5))

plot(density(model_1.np$grad[,4]), sub = "Meats - income elasticity", main= "", xlim=c(-5,5))
plot(density(model_2.np$grad[,4]), sub = "Dairy - income elasticity", main= "",xlim=c(-5,5))
plot(density(model_3.np$grad[,4]), sub = "Pulses - income elasticity", main= "", xlim=c(-5,5))

e3x_np_t <- list()
e3x_np_t$e31_np_t <- mean(model_3.np$grad[,1])/mean(model_3.np$gerr[,1])
e3x_np_t$e32_np_t <- mean(model_3.np$grad[,2])/mean(model_3.np$gerr[,2])
e3x_np_t$e33_np_t <- mean(model_3.np$grad[,3])/mean(model_3.np$gerr[,3])
e3x_np_t$eta3_np_t <- mean(model_3.np$grad[,4])/mean(model_3.np$gerr[,4])

exx_np <- matrix(unlist(c(e1x_np, e2x_np, e3x_np)), nrow = 3, byrow = TRUE)
exx_np_t <- matrix(unlist(c(e1x_np_t, e2x_np_t, e3x_np_t)), nrow = 3, byrow = TRUE)

#########################################
### Full AIDS Model empirical results ###
#########################################
priceNames <- c("p1", "p2", "p3")
shareNames <- c("w1", "w2", "w3")


AIDS_estResult_constraint <- aidsEst( priceNames, shareNames, "X",
                       data = Dta_sub,
                       method = "IL", ILmaxiter = 1000, ILtol = 1e-10,
                       priceIndex = "S", hom = TRUE, sym = TRUE)

AIDS_estResult_no_constraint <- aidsEst( priceNames, shareNames, "X",
                       data = Dta_sub,
                       method = "IL", ILmaxiter = 1000, ILtol = 1e-10,
                       priceIndex = "S", hom = FALSE, sym = FALSE)

#summary(AIDS_estResult_constraint)
#summary(AIDS_estResult_no_constraint)

##############################
### Full AIDS elasticities ###
##############################
AIDS_elas_M_H_income_constraint <- elas( AIDS_estResult_constraint, method = "AIDS" )
AIDS_elas_M_H_income_no_constraint <- elas( AIDS_estResult_no_constraint, method = "AIDS" )


###     ###
# weights <- c( lnp1_catfish=mean(Dta_sub$lnp1_catfish), lnp2_crawfish=mean(Dta_sub$lnp2_crawfish), lnp3_clams=mean(Dta_sub$lnp3_clams), lnp4_shrimp=mean(Dta_sub$lnp4_shrimp), lnp5_tilapia=mean(Dta_sub$lnp5_tilapia), lnp6_salmon=mean(Dta_sub$lnp6_salmon))
# 
# weights <- weights/sum(weights)
# 
# est1_np <- npregHom(yName = "lnq1_catfish", xNames = c("lnp1_catfish", "lnp2_crawfish", "lnp3_clams", "lnp4_shrimp", "lnp5_tilapia", "lnp6_salmon", "lnX"), data=Dta_sub, homWeights = weights)
# 
# est2_np <- npregHom(yName = "lnq2_crawfish", xNames = c("lnp1_catfish", "lnp2_crawfish", "lnp3_clams", "lnp4_shrimp", "lnp5_tilapia", "lnp6_salmon", "lnX"), data=Dta_sub, homWeights = weights)
# 
# e1x_np <- list()
# e1x_np$e11 <- mean(est1_np$est$grad[,1])
# e1x_np$e12 <- mean(est1_np$est$grad[,2])
# e1x_np$e13 <- mean(est1_np$est$grad[,3])
# e1x_np$e14 <- mean(est1_np$est$grad[,4])
# e1x_np$e15 <- mean(est1_np$est$grad[,5])
# e1x_np$e16 <- mean(est1_np$est$grad[,6])
# 
# e2x_np <- list()
# e2x_np$e21 <- mean(est2_np$est$grad[,1])
# e2x_np$e22 <- mean(est2_np$est$grad[,2])
# e2x_np$e23 <- mean(est2_np$est$grad[,3])
# e2x_np$e24 <- mean(est2_np$est$grad[,4])
# e2x_np$e25 <- mean(est2_np$est$grad[,5])
# e2x_np$e26 <- mean(est2_np$est$grad[,6])
# 

```
  
```{r Full AIDS Output, echo=FALSE, message=FALSE, results='asis'}

stargazer(exx_par, header=F, type="latex", summary = FALSE, font.size = "small", notes= c("***Significant at the 1 percent level,", "**Significant at the 5 percent level,", "*Significant at the 10 percent level."), notes.align= "r", flip = F, float = T, float.env = "table", title="Parametric")

stargazer(exx_np, header=F, type="latex", summary = FALSE, font.size = "small", notes= c("***Significant at the 1 percent level,", "**Significant at the 5 percent level,", "*Significant at the 10 percent level."), notes.align= "r", flip = F, float = T, float.env = "table", title="Nonparametric")

stargazer(AIDS_elas_M_H_income_constraint$marshall, header=F, type="latex", summary = FALSE, font.size = "small", notes= c("***Significant at the 1 percent level,", "**Significant at the 5 percent level,", "*Significant at the 10 percent level."), notes.align= "r", flip = F, float = T, float.env = "table", title="Full AIDS - Hicksian")

#stargazer(AIDS_a_b_eta, header=F, type="latex", summary = FALSE, font.size = "small", notes= c("***Significant at the 1 percent level,", "**Significant at the 5 percent level,", "*Significant at the 10 percent level."), notes.align= "r", flip = F, float = T, float.env = "table", title="Full AIDS - Alpha, and Beta parameter estimates, Average Budget Shares, and Income Elasticities")

```